- name: Install 3tier-app(configuration)
  hosts: all
  gather_facts: false
  become: true

  roles:
   - configration

- name: Import In-memory inventory play
  import_playbook: in-memory-inventory.yml

- name: Install 3tier-app(lb-tier)
  hosts: frontends
  gather_facts: false
  become: true

  roles:
    - lb-tier

- name: Install 3tier-app(app-tier)
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - app-tier

- name: Install 3tier-app(db-tier)
  hosts: appdbs
  gather_facts: true
  become: true

  roles:
    - geerlingguy.postgresql
  #  - db-tier
