---
# tasks file for configration
- name: enable repos
  copy:
    src: ../files/open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: Delete internal.repo
  file:
    path: /etc/yum.repos.d/internal.repo
    state: absent
