---
# tasks file for db-tier

- name: install "{{ payload }}-server"
  yum: 
    name: "{{ payload }}-server"
    state: latest

#- name: inittialize PostgreSQL Server


- name: enable "{{ payload }}"  at boot
  service:
    name: "{{ payload }}"
    enabled: yes
