---
# tasks file for win_service_config

- name: install OpenSSH service
  win_chocolatey:
    name: "{{ package_name }}"
    package_params: "{{ parameters }}"
    state: present
  register: result

- name: Start ssh service
  win_service:
    name: "{{ service_name }}"
    state: started

- name: Firawall rule to allow SSH on TCP "{{ local_port }}"
  win_firewall_rule:
    name: SSH
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes


#- name: show previous shell stdout
#  debug:
#    msg: "{{ result }}" 
